<?php
class ShopManagerOrders implements Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'Shop Manager: Orders',
			'summary' => 'Order management for Shop module',
			'version' => 001,
			'permanent' => false,
			'singular' => true,
			'permission' => 'shop_manage',
			'requires' => array('ShopManager')
		);
	}
	
	public function ___install() {
		$admin_id = $this->fuel('config')->adminRootPageID;
		$manager = $this->fuel('pages')->get($admin_id)->child('name=shop, template=admin');
		if($manager->id > 0) {
			$template = $this->fuel('templates')->get('admin');		
			$orders = new page($template);
			$orders->parent = $manager;
			$orders->title = 'Orders';
			$orders->name = 'orders';
			$orders->process = $this;
			$orders->save();		
			$this->message('Installed module: '.$this->className());
			$this->message('Created page: '.$orders->path);
		} else {
			throw new WireException('WasnÕt able to find Shop Manager page!');
		}
	}
	
	public function ___uninstall() {
		$admin_id = $this->fuel('config')->adminRootPageID;
		$manager = $this->fuel('pages')->get($admin_id)->child('name=shop, template=admin');
		$orders = $manager->child('name=orders, template=admin');
		if($orders->id) {
			$path = $orders->path;
			$this->fuel('pages')->delete($orders, true);
			$this->message('Deleted page: '.$path);
		}
	}
}