<?php
class ShopManagerProducts implements  Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'Shop Manager: Products',
			'summary' => 'Products management for Shop module',
			'version' => 001,
			'permanent' => false,
			'singular' => true,
			'permission' => 'shop_manage',
			'requires' => array('ShopManager')
		);
	}
	
	public function ___install() {
		$admin_id = $this->fuel('config')->adminRootPageID;
		$manager = $this->fuel('pages')->get($admin_id)->child('name=shop, template=admin');
		if($manager->id > 0) {
			$template = $this->fuel('templates')->get('admin');
			$customers = new page($template);
			$customers->parent = $manager;
			$customers->title = 'Customers';
			$customers->name = 'customers';
			$customers->process = $this;
			$customers->save();
			$this->message('Installed module: '.$this->className());
			$this->message('Created page: '.$customers->path);
		} else {
			throw new WireException('WasnÕt able to find Shop Manager page!');
		}
	}
	
	public function ___uninstall() {
		$admin_id = $this->fuel('config')->adminRootPageID;
		$manager = $this->fuel('pages')->get($admin_id)->child('name=shop, template=admin');
		$customers = $manager->child('name=customers, template=admin');
		if($customers->id) {
			$path = $customers->path;
			$this->fuel('pages')->delete($customers, true);
			$this->message('Deleted page: '.$path);
		}
	}
}